### ISSUE TITLE
Uncaught Error: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by yuis-ice** [jikan-me/jikan#330]
Hi. 

I Installed jikan with: 

$ composer require jikan-me/jikan

PHP version is: 

$ php -v 
PHP 7.3.24-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 31 2020 16:59:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.24, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.24-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies     

The php file, from the tutorial, is: 

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Jikan\Jikan;

$jikan = new Jikan;

$anime = $jikan->Anime(21);
``` 

I did run the file with; and got an error like: 

```
$ php tmp.php
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /home/yuis/pg/mal/tmp/vendor/symfony/dom-crawler/Crawler.php:1129
Stack trace:
#0 /home/yuis/pg/mal/tmp/vendor/symfony/dom-crawler/Crawler.php(1247): Symfony\Component\DomCrawler\Crawler->parseXhtml('\n<!DOCTYPE html...', 'utf-8')
#1 /home/yuis/pg/mal/tmp/vendor/symfony/dom-crawler/Crawler.php(185): Symfony\Component\DomCrawler\Crawler->parseHtmlString('\n<!DOCTYPE html...', 'utf-8')
#2 /home/yuis/pg/mal/tmp/vendor/symfony/dom-crawler/Crawler.php(169): Symfony\Component\DomCrawler\Crawler->addHtmlContent('\n<!DOCTYPE html...', 'utf-8')
#3 /home/yuis/pg/mal/tmp/vendor/symfony/browser-kit/AbstractBrowser.php(511): Symfony\Component\DomCrawler\Crawler->addContent('\n<!DOCTYPE html...', 'text/html; char...')
#4 /home/yuis/pg/mal/tmp/vendor/symfony/browser-kit/AbstractBrowser.php(405): Symfony\Component\BrowserKit\AbstractBrowser->createCrawlerFromContent('https://myanime...', '\n<!DOCTYPE html...', 'text/html; char...')
#5 /home/yuis/pg/mal/tmp/vendor/jikan-me/jika in /home/yuis/pg/mal/tmp/vendor/symfony/dom-crawler/Crawler.php on line 1129
```

I'm new to here and noob to php so maybe this is not a bug, but I hope this issue and your answer helps other new folks. thanks.

**Comment by irfan-dahir** [comment]
Try installing the PHP DOM dep.

`apt-get install php7.3-xml` for ubuntu

**Comment by yuis-ice** [comment]
solved. thanks.
